# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_dialog_OptimizeDrilling.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(377, 239)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 200, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_param_set_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_param_set_2.setGeometry(QtCore.QRect(10, 70, 351, 101))
        self.groupBox_param_set_2.setObjectName("groupBox_param_set_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_param_set_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 351, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.WOB_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.WOB_max.setDecimals(3)
        self.WOB_max.setMaximum(1000000.0)
        self.WOB_max.setSingleStep(0.0)
        self.WOB_max.setProperty("value", 90000.0)
        self.WOB_max.setObjectName("WOB_max")
        self.gridLayout.addWidget(self.WOB_max, 1, 2, 1, 1)
        self.WURF_RPM_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.WURF_RPM_max.setDecimals(8)
        self.WURF_RPM_max.setProperty("value", 2.5)
        self.WURF_RPM_max.setObjectName("WURF_RPM_max")
        self.gridLayout.addWidget(self.WURF_RPM_max, 2, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 1, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 0, 2, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 2, 0, 1, 1)
        self.WOB_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.WOB_min.setDecimals(3)
        self.WOB_min.setMaximum(1000000.0)
        self.WOB_min.setProperty("value", 20000.0)
        self.WOB_min.setObjectName("WOB_min")
        self.gridLayout.addWidget(self.WOB_min, 1, 1, 1, 1)
        self.WURF_RPM_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.WURF_RPM_min.setDecimals(8)
        self.WURF_RPM_min.setProperty("value", 1.5)
        self.WURF_RPM_min.setObjectName("WURF_RPM_min")
        self.gridLayout.addWidget(self.WURF_RPM_min, 2, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(26, 20, 71, 20))
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setObjectName("label_3")
        self.comboBox_perforated_interval = QtWidgets.QComboBox(Dialog)
        self.comboBox_perforated_interval.setGeometry(QtCore.QRect(100, 20, 251, 22))
        self.comboBox_perforated_interval.setObjectName("comboBox_perforated_interval")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_param_set_2.setTitle(_translate("Dialog", "钻井参数优化范围设置"))
        self.label_50.setText(_translate("Dialog", "WOB"))
        self.label_54.setText(_translate("Dialog", "max"))
        self.label_57.setText(_translate("Dialog", "WURF_RPM"))
        self.label_53.setText(_translate("Dialog", "min"))
        self.label_3.setText(_translate("Dialog", "优化段选择："))
