# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_sweetAreaSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(292, 269)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(90, 230, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_param_set = QtWidgets.QGroupBox(Dialog)
        self.groupBox_param_set.setGeometry(QtCore.QRect(10, 20, 271, 201))
        self.groupBox_param_set.setObjectName("groupBox_param_set")
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_param_set)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 251, 171))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_46 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_46.setObjectName("label_46")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.label_47 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_47.setObjectName("label_47")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.label_48 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_48.setObjectName("label_48")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_38.setObjectName("label_38")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_39.setObjectName("label_39")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_40.setObjectName("label_40")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.sg_threshold = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_8)
        self.sg_threshold.setDecimals(3)
        self.sg_threshold.setProperty("value", 0.1)
        self.sg_threshold.setObjectName("sg_threshold")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sg_threshold)
        self.por_threshold = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_8)
        self.por_threshold.setDecimals(3)
        self.por_threshold.setProperty("value", 0.03)
        self.por_threshold.setObjectName("por_threshold")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.por_threshold)
        self.sw_threshold = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_8)
        self.sw_threshold.setDecimals(3)
        self.sw_threshold.setProperty("value", 0.8)
        self.sw_threshold.setObjectName("sw_threshold")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sw_threshold)
        self.perm_threshold = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_8)
        self.perm_threshold.setDecimals(4)
        self.perm_threshold.setProperty("value", 0.4)
        self.perm_threshold.setObjectName("perm_threshold")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.perm_threshold)
        self.pressure_threshold = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_8)
        self.pressure_threshold.setDecimals(2)
        self.pressure_threshold.setMaximum(100000.0)
        self.pressure_threshold.setProperty("value", 100.0)
        self.pressure_threshold.setObjectName("pressure_threshold")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pressure_threshold)
        self.temperature_threshold = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_8)
        self.temperature_threshold.setDecimals(2)
        self.temperature_threshold.setMinimum(-1000.0)
        self.temperature_threshold.setMaximum(10000.0)
        self.temperature_threshold.setProperty("value", 150.0)
        self.temperature_threshold.setObjectName("temperature_threshold")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.temperature_threshold)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_param_set.setTitle(_translate("Dialog", "自定义条件寻找甜点区"))
        self.label_46.setText(_translate("Dialog", "por_threshold"))
        self.label_47.setText(_translate("Dialog", "sw_threshold"))
        self.label_48.setText(_translate("Dialog", "sg_threshold"))
        self.label_38.setText(_translate("Dialog", "perm_threshold"))
        self.label_39.setText(_translate("Dialog", "pressure_threshold"))
        self.label_40.setText(_translate("Dialog", "temperature_threshold"))
